name: Podman Image CI

on:
  push:
    branches: [ "main", "demo" ]

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/iublibtech
  IMAGE_TAG: fromJSON('{"refs/heads/main":"develop","refs/heads/demo":"production"}')[github.ref]
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Yarn build
      # Explicitly set CI to false to avoid elevating warnings to errors
      run: yarn install && CI=false yarn build
    - name: Build Image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: timeliner
        tags: ${{ env.IMAGE_TAG }} ${{ github.sha }}
        containerfiles: ./Dockerfile
        oci: true
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust
